// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvinapqmcmbpyjpwpgms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52aW5hcHFtY21icHlqcHdwZ21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDgxNTMsImV4cCI6MjA2MDk4NDE1M30.RUlNI5Yweh9OY1LZPASlwejPoCGOeeTucK5IfYZTJdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);